### ISSUE TITLE
Runtime error on some win10 platform

### ISSUE THREAD

**Issue by ychding11** [ychding11/CUDAStudy#1]
## Error describe
*** WARNING - PE SIGNATURE VERIFICATION FAILED !!!
*** Filename: C:\Program Files\NVIDIA Corporation\Ansel\Tools\NvCameraWhitelisting64.dll
*** Error: 0x80092009
D3D11CreateDevice: Flags (0x2) were specified which require the D3D11 SDK Layers for Windows 10, but they are not present on the system.
These flags must be removed, or the Windows 10 SDK must be installed.
Flags include: D3D11_CREATE_DEVICE_DEBUG
Exception thrown at 0x00007FFA97863C58 in OGSTestApp.exe: Microsoft C++ exception: _com_error at memory location 0x0000000000148D50.

**Comment by ychding11** [comment]
## Errors when installing "Graphics Tools" on Windows 10 platform
- [No available optional features](https://answers.microsoft.com/en-us/windows/forum/windows_10-other_settings-winpc/windows-10-optional-features-missing/c9555e72-11ed-416a-bc65-1a8372fc27ab?auth=1), This is because: 
  - **UseWUServer** in _KEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU_  is set to one.
  - It means using a custom update server (e.g. one on the domain). 
- Solution: [install-d3d11-sdk-layers-for-windows-10-offline-by-dism](https://stackoverflow.com/questions/34318515/how-to-install-d3d11-sdk-layers-for-windows-10-offline/34347665#34347665)

**Comment by ychding11** [comment]
## How does an app decide its windows sdk version when running ?

**Comment by ychding11** [comment]
## Solution

**Comment by tajuddinkhandaker** [comment]
I have uninstalled and removed the package both x86 and x64 "Graphics Tool" from windows 10. But still the following runtime error exists. I don't want to debug API but I add the debug Flags if SDK layer available. The flag is not added but at runtime it keps showing the below error.

D3D11CreateDevice: Flags (0x2) were specified which require the D3D11 SDK Layers for Windows 10, but they are not present on the system.
These flags must be removed, or the Windows 10 SDK must be installed.
Flags include: D3D11_CREATE_DEVICE_DEBUG

**Comment by ychding11** [comment]
It seems you specified a "debug device creation".  But NO  "Graphics Tool"  found on your system.
If you don't want  a "debug device", don't specify it by creation flag.
